--- #YAML:1.0
name: File-MergeSort
abstract: Mergesort ordered files
version: 1.15
author:
  - Barrie Bremner (BREMNERB)
  - Chris Brown (CTBROWN)
installdirs: site
license: perl
requires:
    IO::File:                      0
    Test::More:                    0
recommends:
    IO::Zlib                       0
    Test::Pod::Coverage            1.00
    Test::Pod                      1.00
distribution_type: module
meta-spec:
  version: 1.4
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Barrie Bremner
